name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.1
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
